### ISSUE TITLE
install issue on Py 3.9 ubuntu

### ISSUE THREAD

**Issue by microprediction** [linkedin/greykite#53]
First, the workaround: 

    pip install --upgrade numpy
    pip install osqp==0.6.1
    pip install greykite 

However, when installing on 3.9

     pip install greykite 

 I get a dep reconcilement error ... though not for python 3.8 or 3.7 

Then, when trying:

      pip install osqp==0.6.1
      pip install greykite 

on [this run](https://github.com/microprediction/timemachines/actions/runs/1259793518) we fail with the following trace so maybe this is really an issue for osqp. 

  ```
Collecting osqp==0.6.1
    Downloading osqp-0.6.1.tar.gz (211 kB)
      ERROR: Command errored out with exit status 1:
       command: /opt/hostedtoolcache/Python/3.9.7/x64/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-zyakqj8s/osqp_44d9cc4bcb2443fd871eaf19a373922d/setup.py'"'"'; __file__='"'"'/tmp/pip-install-zyakqj8s/osqp_44d9cc4bcb2443fd871eaf19a373922d/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-k6piad63
           cwd: /tmp/pip-install-zyakqj8s/osqp_44d9cc4bcb2443fd871eaf19a373922d/
      Complete output (5 lines):
      Traceback (most recent call last):
        File "<string>", line 1, in <module>
        File "/tmp/pip-install-zyakqj8s/osqp_44d9cc4bcb2443fd871eaf19a373922d/setup.py", line 11, in <module>
          import numpy
      ModuleNotFoundError: No module named 'numpy'
      ----------------------------------------
  WARNING: Discarding https://files.pythonhosted.org/packages/ba/17/49790ce2ce7a6b95cd250642ebc68bd723ddefdd052ee8dcc1e0dcf4ffca/osqp-0.6.1.tar.gz#sha256=47b17996526d6ecdf35cfaead6e3e05d34bc2ad48bcb743153cefe555ecc0e8c (from https://pypi.org/simple/osqp/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  ERROR: Could not find a version that satisfies the requirement osqp==0.6.1 (from versions: 0.1.3, 0.2.0, 0.2.1, 0.3.0, 0.4.0, 0.4.1, 0.5.0, 0.6.0, 0.6.1, 0.6.2, 0.6.2.post0)
```

**Comment by ianlcassidy** [comment]
i'm also having this problem. seems that osqp 0.6.2 fixes this problem. greykite would have to bump the osqp dependency.
