### ISSUE TITLE
error : "NaTType does not support strftime"

### ISSUE THREAD

**Issue by orydatadudes** [linkedin/greykite#7]
i am trying using greykite on kaggle monthly-beer-production-in-austr data set :
df = pd.read_csv('data/monthly-beer-production-in-austr.csv')
df.Month = pd.to_datetime(df['Month'])
df.head()

<div class="output"><div class="output_area"></div></div><div>

&nbsp; | Month | Monthly beer production
-- | -- | --
1956-01-01 | 93.2
1956-02-01 | 96.0
1956-03-01 | 95.2
1956-04-01 | 77.1
1956-05-01 | 70.9

</div>
then when follow simple forecast orders:

metadata = MetadataParam(
     time_col="Month", 
     value_col="Monthly beer production", 
     freq="M"  
 )
    
forecaster = Forecaster()
result = forecaster.run_forecast_config(
     df=df,
     config=ForecastConfig(
         model_template=ModelTemplateEnum.SILVERKITE.name,
         forecast_horizon=test_period,  
         metadata_param=metadata
     )
 )

i got the following error:

Traceback (most recent call last):
  File "/home/pycharm/pycharm-community-2020.1.2/plugins/python-ce/helpers/pydev/pydevd.py", line 1438, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/pycharm/pycharm-community-2020.1.2/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/projects/time_sseries_compering/temp.py", line 38, in <module>
    metadata_param=metadata
  File "/home/anaconda3/envs/icl/lib/python3.7/site-packages/greykite/framework/templates/forecaster.py", line 288, in run_forecast_config
    config=config)
  File "/home/anaconda3/envs/icl/lib/python3.7/site-packages/greykite/framework/templates/forecaster.py", line 257, in apply_forecast_config
    self.pipeline_params = self.template.apply_template_for_pipeline_params(df=df, config=self.config)
  File "/home/anaconda3/envs/icl/lib/python3.7/site-packages/greykite/framework/templates/base_template.py", line 250, in process_wrapper
    pipeline_params = func(self, df, config)
  File "/home/anaconda3/envs/icl/lib/python3.7/site-packages/greykite/framework/templates/base_template.py", line 287, in apply_template_for_pipeline_params
    self.time_properties = self.get_forecast_time_properties()
  File "/home/or/anaconda3/envs/icl/lib/python3.7/site-packages/greykite/framework/templates/base_template.py", line 208, in get_forecast_time_properties
    forecast_horizon=self.config.forecast_horizon)
  File "/home/or/anaconda3/envs/icl/lib/python3.7/site-packages/greykite/common/time_properties_forecast.py", line 159, in get_forecast_time_properties
    start_year = int(train_start.strftime("%Y"))
  File "pandas/_libs/tslibs/nattype.pyx", line 69, in pandas._libs.tslibs.nattype._make_error_func.f
ValueError: NaTType does not support strftime

changing freq for something else (like (W) work fine
what am i doing wrong 
thank you

**Comment by al-bert** [comment]
Try using freq="MS" (instead of "M") to represent month start frequency. Reference: https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#offset-aliases

(If you don't have any missing dates, you can simply omit the freq parameter and greykite will infer it for you.)

**Comment by orydatadudes** [comment]
thank you , solved
