### ISSUE TITLE
Different Precision Causes IndexError

### ISSUE THREAD

**Issue by ikegwukc** [linkedin/greykite#70]
Hello,

Different precision of variable types causes an index error exactly like the one found in #64 

If I change the precision of my target variable Greykite throws an error. Should the amount of bits used cause an IndexError?

I created a minimum working example.  Below I change the precision of y in the Peyton Manning Example from `float64` to `float32` it throws an error.
 
Example:
```python
from greykite.common.data_loader import DataLoader
from greykite.framework.templates.autogen.forecast_config import ForecastConfig
from greykite.framework.templates.autogen.forecast_config import MetadataParam
from greykite.framework.templates.forecaster import Forecaster
from greykite.framework.templates.model_templates import ModelTemplateEnum
from greykite.framework.utils.result_summary import summarize_grid_search_results

# Loads dataset into pandas DataFrame
dl = DataLoader()
df = dl.load_peyton_manning()

# copy pd.Dataframe and change precision
df2 = df.copy()
df2.y = df2.y.astype('float32')


# specify dataset information
metadata = MetadataParam(
   time_col="ts",  # name of the time column ("date" in example above)
   value_col="y",  # name of the value column ("sessions" in example above)
   freq="D"  # "H" for hourly, "D" for daily, "W" for weekly, etc.

forecaster = Forecaster()  # Creates forecasts and stores the result
result = forecaster.run_forecast_config(  # result is also stored as `forecaster.forecast_result`.
     df=df2,
     config=ForecastConfig(
         model_template=ModelTemplateEnum.SILVERKITE.name,
         forecast_horizon=365,  # forecasts 365 steps ahead
         coverage=0.95,         # 95% prediction intervals
         metadata_param=metadata
     )
 )            
```
> Fitting 3 folds for each of 1 candidates, totalling 3 fits
/databricks/python/lib/python3.8/site-packages/greykite/algo/forecast/silverkite/forecast_simple_silverkite_helper.py:129: UserWarning: Requested holiday 'Easter Monday [England, Wales, Northern Ireland]' does not occur in the provided countries
  warnings.warn(
/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py", line 593, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/databricks/python_shell/dbruntime/MLWorkloadsInstrumentation/_sklearn.py", line 29, in patch_function
    original_result = original(self, *args, **kwargs)
  File "/databricks/python/lib/python3.8/site-packages/sklearn/pipeline.py", line 346, in fit
    self._final_estimator.fit(Xt, y, **fit_params_last_step)
  File "/databricks/python/lib/python3.8/site-packages/greykite/sklearn/estimator/simple_silverkite_estimator.py", line 250, in fit
    self.model_dict = self.silverkite.forecast_simple(
  File "/databricks/python/lib/python3.8/site-packages/greykite/algo/forecast/silverkite/forecast_simple_silverkite.py", line 747, in forecast_simple
    trained_model = super().forecast(**parameters)
  File "/databricks/python/lib/python3.8/site-packages/greykite/algo/forecast/silverkite/forecast_silverkite.py", line 939, in forecast
    trained_model = fit_ml_model_with_evaluation(
  File "/databricks/python/lib/python3.8/site-packages/greykite/algo/common/ml_models.py", line 806, in fit_ml_model_with_evaluation
    training_evaluation[R2_null_model_score] = r2_null_model_score(
  File "/databricks/python/lib/python3.8/site-packages/greykite/common/evaluation.py", line 333, in r2_null_model_score
    y_true, y_pred, y_train, y_pred_null = valid_elements_for_evaluation(
  File "/databricks/python/lib/python3.8/site-packages/greykite/common/evaluation.py", line 157, in valid_elements_for_evaluation
    return [array[keep] for array in reference_arrays] + [np.array(array)[keep] if (
  File "/databricks/python/lib/python3.8/site-packages/greykite/common/evaluation.py", line 157, in <listcomp>
    return [array[keep] for array in reference_arrays] + [np.array(array)[keep] if (
IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed
>

**Comment by ikegwukc** [comment]
So far, my fix is to convert my target variable from float32 to float64 and then it runs fine but I do not think precision should cause an error like this.

**Comment by KaixuYang** [comment]
Hi @ikegwukc Thanks for raising this issue! We are aware of this issue and will fix it in the next release!
